# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842937198b86338cb3936ee85fdfa8063f3c4e712adc2fccd69780a40d86959b731dc515beaabca589efb2916ce1c71bb3986f394c78b94581313a4d3320e29a

test:
  secret_key_base: 801bf63fa3e83193dc7e320b46feb8f7e0976f9a5b5ad04303d336286ad5ca773a3e8e72c0510daf59d1a55201786b03fb28fe64e29471aa699a9d5c66812725

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
